security:
  user:
    name: buzz
    password: infinity

taco:
  orders:
    pageSize: 10


  discount:
    codes:
      abcdef: 10

spring:
#  main:
#    web-application-type: reactive # 리액티브 애플리케이션을 사용하려면 지정합니다

  data:
    rest:
      base-path: /data-api
    mongodb:
      uri: mongodb://localhost:27017/tacocloud

    #---
#spring:
#  profiles: prod
  
#  datasource:
#    url: jdbc:mysql://localhost:3306/tacocloud
#    username: root
#    password: 1234

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: "jdbc:mysql://localhost:3306/tacocloud?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&tinyInt1isBit=false"
#    username: root
#    password: 1234
    
    
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      pool-name: pool-tacocloud_db

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        "[format_sql]": true            #SQL을 보기 좋게 출력
        "[user_sql_comments]": true     #SQL생성 시 주석 포함
        "[highlight_sql]": true         #SQL에 색깔
        "[hbm2ddl.auto]": create
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        #physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    open-in-view: false
    show-sql: true

  # tacocloud-messaging-kafka의 yml 파일은 적용이 안됨. root 경로만 가능하다?
  kafka:
    bootstrap-servers:
      - 15.164.212.231:9092
    template:
      default-topic: tacocloud_orders
    producer:
      keySerializer: org.springframework.kafka.support.serializer.JsonSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org.springframework.data.mongodb.core: DEBUG
